/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.kma.sms.ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RadialGradientPaint;
import java.awt.RenderingHints;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import javax.swing.ImageIcon;

/**
 *
 * @author lxsgo
 */
public class MainForm extends javax.swing.JFrame {

    /* Card layout */
    private void initCardLayout() {
        CardLayout cardLayout = new CardLayout();
        contentPanel.setLayout(cardLayout);
        contentPanel.add(new HomePagePanel(), "homePagePanel");
        contentPanel.add(new MajorManagePanel(), "majorManagePanel");
        contentPanel.add(new ClassManagePanel(), "classManagePanel");
        contentPanel.add(new SubjectManagePanel(), "subjectManagePanel");
        contentPanel.add(new StudentManagePanel(), "studentManagePanel");
        contentPanel.add(new ScoreManagePanel(), "scoreManagePanel");
        // cardLayout.show(contentPanel, "homePagePanel");

        // always fit the content panel to the parent panel
        this.pack();
        contentPanel.revalidate();
    }

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        initCardLayout();

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        

        headerPanel = new javax.swing.JPanel() {

            private final ImageIcon imageIcon = new ImageIcon("src/main/resources/images/cat_logo.png");
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                Graphics2D g2d = (Graphics2D) grphcs;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Load the properties file
                Properties prop = new Properties();
                try (InputStream input = new FileInputStream("src/main/resources/background.properties")) {
                    prop.load(input);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }

                // Extract and parse the color values
                Color[] colors = new Color[3];
                String[] colorStrings = prop.getProperty("colors_set_1").split(", "); // Change this to use different
                                                                                      // color sets
                for (int i = 0; i < colorStrings.length; i++) {
                    colors[i] = Color.decode(colorStrings[i]);
                }

                int diameter = Math.max(getWidth(), getHeight());
                float radius = diameter * 1.0f; // Increase the radius
                float[] dist = { 0.0f, 0.5f, 1.0f };
                RadialGradientPaint rgp = new RadialGradientPaint(getWidth() - 50, getHeight() - 50, radius, dist,
                        colors);

                g2d.setPaint(rgp);
                g2d.fillRect(0, 0, getWidth(), getHeight());

                // Draw the image
                Image image = imageIcon.getImage();

                g2d.drawImage(image, getWidth() - 125, -10, 125, 125, null);
            }

        };
        bannerText = new javax.swing.JLabel();
        naviPanel = new javax.swing.JPanel();
        homePageNaviButton = new javax.swing.JButton();
        departmentDirNaviButton = new javax.swing.JButton();
        classDirNaviButton = new javax.swing.JButton();
        subjectManageNaviButton = new javax.swing.JButton();
        studentManageNaviButton = new javax.swing.JButton();
        scoreMangeNaviButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bannerText.setBackground(new java.awt.Color(51, 0, 51));
        bannerText.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        bannerText.setForeground(new java.awt.Color(255, 255, 255));
        bannerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bannerText.setText("QUẢN LÝ SINH VIÊN");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(bannerText, javax.swing.GroupLayout.PREFERRED_SIZE, 283,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(484, Short.MAX_VALUE)));
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                                .addContainerGap(39, Short.MAX_VALUE)
                                .addComponent(bannerText)
                                .addGap(38, 38, 38)));

        homePageNaviButton.setBackground(new java.awt.Color(38, 117, 191));
        homePageNaviButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homePageNaviButton.setForeground(new java.awt.Color(255, 255, 255));
        homePageNaviButton.setText("Trang chủ");
        homePageNaviButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        homePageNaviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageNaviButtonActionPerformed(evt);
            }
        });

        departmentDirNaviButton.setBackground(new java.awt.Color(38, 117, 191));
        departmentDirNaviButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        departmentDirNaviButton.setForeground(new java.awt.Color(255, 255, 255));
        departmentDirNaviButton.setText("Danh mục khoa");
        departmentDirNaviButton
                .setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        departmentDirNaviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentDirNaviButtonActionPerformed(evt);
            }
        });

        classDirNaviButton.setBackground(new java.awt.Color(38, 117, 191));
        classDirNaviButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        classDirNaviButton.setForeground(new java.awt.Color(255, 255, 255));
        classDirNaviButton.setText("Danh mục lớp");
        classDirNaviButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        classDirNaviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classDirNaviButtonActionPerformed(evt);
            }
        });

        subjectManageNaviButton.setBackground(new java.awt.Color(38, 117, 191));
        subjectManageNaviButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subjectManageNaviButton.setForeground(new java.awt.Color(255, 255, 255));
        subjectManageNaviButton.setText("Quản lý môn");
        subjectManageNaviButton
                .setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        subjectManageNaviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectManageNaviButtonActionPerformed(evt);
            }
        });

        studentManageNaviButton.setBackground(new java.awt.Color(38, 117, 191));
        studentManageNaviButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentManageNaviButton.setForeground(new java.awt.Color(255, 255, 255));
        studentManageNaviButton.setText("Quản lý sv");
        studentManageNaviButton
                .setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        studentManageNaviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentManageNaviButtonActionPerformed(evt);
            }
        });

        scoreMangeNaviButton.setBackground(new java.awt.Color(38, 117, 191));
        scoreMangeNaviButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        scoreMangeNaviButton.setForeground(new java.awt.Color(255, 255, 255));
        scoreMangeNaviButton.setText("Quản lý điểm");
        scoreMangeNaviButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        scoreMangeNaviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreMangeNaviButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout naviPanelLayout = new javax.swing.GroupLayout(naviPanel);
        naviPanel.setLayout(naviPanelLayout);
        naviPanelLayout.setHorizontalGroup(
                naviPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(homePageNaviButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(departmentDirNaviButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124,
                                Short.MAX_VALUE)
                        .addComponent(classDirNaviButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subjectManageNaviButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentManageNaviButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scoreMangeNaviButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        naviPanelLayout.setVerticalGroup(
                naviPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(naviPanelLayout.createSequentialGroup()
                                .addComponent(homePageNaviButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(departmentDirNaviButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(classDirNaviButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(subjectManageNaviButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(studentManageNaviButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(scoreMangeNaviButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 160, Short.MAX_VALUE)));

        contentPanel.setPreferredSize(new java.awt.Dimension(600, 1000));
        contentPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                contentPanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
                contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        contentPanelLayout.setVerticalGroup(
                contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(naviPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 677,
                                                        Short.MAX_VALUE)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(naviPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 353,
                                                Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentDirNaviButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_departmentDirNaviButtonActionPerformed
        // Show major manage panel and hide other panels
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "majorManagePanel");

    }// GEN-LAST:event_departmentDirNaviButtonActionPerformed

    private void classDirNaviButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_classDirNaviButtonActionPerformed
        // Show class manage panel and hide other panels
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "classManagePanel");

    }// GEN-LAST:event_classDirNaviButtonActionPerformed

    private void subjectManageNaviButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_subjectManageNaviButtonActionPerformed
        // Show subject manage panel and hide other panels
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "subjectManagePanel");

    }// GEN-LAST:event_subjectManageNaviButtonActionPerformed

    private void studentManageNaviButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_studentManageNaviButtonActionPerformed
        // show student manage panel and hide other panels
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "studentManagePanel");

    }// GEN-LAST:event_studentManageNaviButtonActionPerformed

    private void scoreMangeNaviButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_scoreMangeNaviButtonActionPerformed
        // show score manage panel and hide other panels
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "scoreManagePanel");

    }// GEN-LAST:event_scoreMangeNaviButtonActionPerformed

    private void contentPanelComponentResized(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_contentPanelComponentResized

    }// GEN-LAST:event_contentPanelComponentResized

    private void homePageNaviButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homePageNaviButtonActionPerformed
        // show homepage
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "homePagePanel");
    }// GEN-LAST:event_homePageNaviButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    System.out.println("Set look and feel to Windows Classic");
                    break;
                }
            }

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                MainForm mainForm = new MainForm();
                mainForm.setLocationRelativeTo(null);

                mainForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerText;
    private javax.swing.JButton classDirNaviButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton departmentDirNaviButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton homePageNaviButton;
    private javax.swing.JPanel naviPanel;
    private javax.swing.JButton scoreMangeNaviButton;
    private javax.swing.JButton studentManageNaviButton;
    private javax.swing.JButton subjectManageNaviButton;
    // End of variables declaration//GEN-END:variables

}
